server:

  applicationConnectors:
    - type: http
      port: 9090
      
  adminConnectors:
    - type: http
      port: 9180
  
logging:
  level: INFO
  loggers:
    com.javaeeeee: DEBUG
